{"uuid":"7a579d37-c422-48b2-b554-d56d242590b7","historyId":"2ed24967452699c6062cc2b036a2f645","fullName":"src/test/resources/features/Array.feature:234","labels":[{"name":"tag","value":"Array"},{"name":"tag","value":"Array25"},{"name":"host","value":"Jibys-MacBook-Air.local"},{"name":"thread","value":"55849@Jibys-MacBook-Air.local.main(1)"},{"name":"feature","value":"User is on Array Page"},{"name":"story","value":"The user is presented with error message for invalid code in tryEditor for Max Consecutive Ones"},{"name":"suite","value":"User is on Array Page"},{"name":"testClass","value":"The user is presented with error message for invalid code in tryEditor for Max Consecutive Ones"},{"name":"framework","value":"cucumber4jvm"},{"name":"language","value":"java"},{"name":"gherkin_uri","value":"file:///Users/jibyraju/eclipse-workspace/Project_101/src/test/resources/features/Array.feature"},{"name":"package","value":"src.test.resources.features.Array_feature.User is on Array Page"}],"links":[],"name":"The user is presented with error message for invalid code in tryEditor for Max Consecutive Ones","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Result do not match expected [NameError: name 'hello' is not defined on line 1] but found [SyntaxError: bad input on line 1]","trace":"java.lang.AssertionError: Result do not match expected [NameError: name 'hello' is not defined on line 1] but found [SyntaxError: bad input on line 1]\n\tat org.testng.Assert.fail(Assert.java:111)\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\n\tat org.testng.Assert.assertEquals(Assert.java:132)\n\tat org.testng.Assert.assertEquals(Assert.java:656)\n\tat StepDefinitions.ArrayStepDefinition.the_user_should_be_presented_with_error_result(ArrayStepDefinition.java:125)\n\tat ✽.The user should be presented with error result(file:///Users/jibyraju/eclipse-workspace/Project_101/src/test/resources/features/Array.feature:230)\n"},"stage":"finished","steps":[{"name":"Given  The user is on Question page of Max Consecutive Ones after logged in","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1697253616052,"stop":1697253616849},{"name":"When  The user enter python code with invalid syntax in tryEditor from sheet  \"pythoncode\" and 1","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1697253616849,"stop":1697253616875},{"name":"And  The user clicks run button","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1697253616875,"stop":1697253616904},{"name":"Then  The user should be presented with error result","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Result do not match expected [NameError: name 'hello' is not defined on line 1] but found [SyntaxError: bad input on line 1]","trace":"java.lang.AssertionError: Result do not match expected [NameError: name 'hello' is not defined on line 1] but found [SyntaxError: bad input on line 1]\n\tat org.testng.Assert.fail(Assert.java:111)\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\n\tat org.testng.Assert.assertEquals(Assert.java:132)\n\tat org.testng.Assert.assertEquals(Assert.java:656)\n\tat StepDefinitions.ArrayStepDefinition.the_user_should_be_presented_with_error_result(ArrayStepDefinition.java:125)\n\tat ✽.The user should be presented with error result(file:///Users/jibyraju/eclipse-workspace/Project_101/src/test/resources/features/Array.feature:230)\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1697253616904,"stop":1697253618927}],"attachments":[],"parameters":[{"name":"Sheetname","value":"pythoncode"},{"name":"RowNumber","value":"1"}],"start":1697253616051,"stop":1697253618928}